# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cache_management_pb2 as cache__management__pb2


class CacheManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportTrainingMetrics = channel.unary_unary(
                '/cache_management.CacheManagement/ReportTrainingMetrics',
                request_serializer=cache__management__pb2.TrainingMetrics.SerializeToString,
                response_deserializer=cache__management__pb2.CachePreloadResponse.FromString,
                )


class CacheManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportTrainingMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportTrainingMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTrainingMetrics,
                    request_deserializer=cache__management__pb2.TrainingMetrics.FromString,
                    response_serializer=cache__management__pb2.CachePreloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache_management.CacheManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CacheManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportTrainingMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache_management.CacheManagement/ReportTrainingMetrics',
            cache__management__pb2.TrainingMetrics.SerializeToString,
            cache__management__pb2.CachePreloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
