# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache_management.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63\x61\x63he_management.proto\x12\x10\x63\x61\x63he_management\"C\n\x0fTrainingMetrics\x12\x18\n\x10order_of_batches\x18\x01 \x03(\x05\x12\x16\n\x0etraining_speed\x18\x02 \x01(\x02\"\'\n\x14\x43\x61\x63hePreloadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2u\n\x0f\x43\x61\x63heManagement\x12\x62\n\x15ReportTrainingMetrics\x12!.cache_management.TrainingMetrics\x1a&.cache_management.CachePreloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_management_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRAININGMETRICS']._serialized_start=44
  _globals['_TRAININGMETRICS']._serialized_end=111
  _globals['_CACHEPRELOADRESPONSE']._serialized_start=113
  _globals['_CACHEPRELOADRESPONSE']._serialized_end=152
  _globals['_CACHEMANAGEMENT']._serialized_start=154
  _globals['_CACHEMANAGEMENT']._serialized_end=271
# @@protoc_insertion_point(module_scope)
