# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: super_dl/protos/cache_coordinator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'super_dl/protos/cache_coordinator.proto\x1a\x1bgoogle/protobuf/empty.proto\"1\n\x16\x42\x61tchAccessPatternList\x12\x17\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\x06.Batch\"0\n\x05\x42\x61tch\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x03\x12\x15\n\rbatch_indices\x18\x02 \x03(\x05\"A\n\x13RegisterJobResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x11job_is_registered\x18\x02 \x01(\x08\"B\n\x07JobInfo\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x61ta_dir\x18\x02 \x01(\t\x12\x15\n\rsource_system\x18\x03 \x01(\t\" \n\x0eMetricsRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t2\xcb\x01\n\x17\x43\x61\x63heCoordinatorService\x12-\n\x0bRegisterJob\x12\x08.JobInfo\x1a\x14.RegisterJobResponse\x12\x36\n\x0bSendMetrics\x12\x0f.MetricsRequest\x1a\x16.google.protobuf.Empty\x12I\n\x16SendBatchAccessPattern\x12\x17.BatchAccessPatternList\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'super_dl.protos.cache_coordinator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATCHACCESSPATTERNLIST']._serialized_start=72
  _globals['_BATCHACCESSPATTERNLIST']._serialized_end=121
  _globals['_BATCH']._serialized_start=123
  _globals['_BATCH']._serialized_end=171
  _globals['_REGISTERJOBRESPONSE']._serialized_start=173
  _globals['_REGISTERJOBRESPONSE']._serialized_end=238
  _globals['_JOBINFO']._serialized_start=240
  _globals['_JOBINFO']._serialized_end=306
  _globals['_METRICSREQUEST']._serialized_start=308
  _globals['_METRICSREQUEST']._serialized_end=340
  _globals['_CACHECOORDINATORSERVICE']._serialized_start=343
  _globals['_CACHECOORDINATORSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
