# Build: sudo docker build -t <project_name> .
# Run: sudo docker run -v $(pwd):/workspace/project --gpus all -it --rm <project_name>

FROM python:3.10

ENV PYTHONIOENCODING=UTF-8
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install -y bash \
                   build-essential \
                   curl \
                   ca-certificates \
                   wget \
    && rm -rf /var/lib/apt/lists

# Install requirements
COPY super_grpc_service_requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/super_grpc_service_requirements.txt \
    && rm /tmp/super_grpc_service_requirements.txt

# Copy project files
# Copy specific folders
COPY ./superdl /workspace/superdl

# Set PYTHONPATH
ENV PYTHONPATH=/workspaces/superdl

WORKDIR /workspace/superdl

CMD ["/bin/bash"]
