# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: superdl/asyncgrpc/protos/cache_coordinator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0superdl/asyncgrpc/protos/cache_coordinator.proto\x1a\x1bgoogle/protobuf/empty.proto\"A\n\x16\x42\x61tchAccessPatternList\x12\x0e\n\x06job_id\x18\x01 \x01(\x03\x12\x17\n\x07\x62\x61tches\x18\x02 \x03(\x0b\x32\x06.Batch\"0\n\x05\x42\x61tch\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x03\x12\x15\n\rbatch_samples\x18\x02 \x01(\t2e\n\x17\x43\x61\x63heCoordinatorService\x12J\n\x17ShareBatchAccessPattern\x12\x17.BatchAccessPatternList\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'superdl.asyncgrpc.protos.cache_coordinator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATCHACCESSPATTERNLIST']._serialized_start=81
  _globals['_BATCHACCESSPATTERNLIST']._serialized_end=146
  _globals['_BATCH']._serialized_start=148
  _globals['_BATCH']._serialized_end=196
  _globals['_CACHECOORDINATORSERVICE']._serialized_start=198
  _globals['_CACHECOORDINATORSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
