# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from superdl.asyncgrpc.protos import cache_coordinator_pb2 as superdl_dot_asyncgrpc_dot_protos_dot_cache__coordinator__pb2


class CacheCoordinatorServiceStub(object):
    """
    Command to create stub files:
    python -m grpc_tools.protoc --proto_path=. ./superdl/asyncgrpc/protos/cache_coordinator.proto --python_out=. --grpc_python_out=.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareBatchAccessPattern = channel.unary_unary(
                '/CacheCoordinatorService/ShareBatchAccessPattern',
                request_serializer=superdl_dot_asyncgrpc_dot_protos_dot_cache__coordinator__pb2.BatchAccessPatternList.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class CacheCoordinatorServiceServicer(object):
    """
    Command to create stub files:
    python -m grpc_tools.protoc --proto_path=. ./superdl/asyncgrpc/protos/cache_coordinator.proto --python_out=. --grpc_python_out=.
    """

    def ShareBatchAccessPattern(self, request, context):
        """rpc RegisterJob(JobInfo) returns (RegisterJobResponse);
        rpc SendMetrics(MetricsRequest) returns (google.protobuf.Empty);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheCoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareBatchAccessPattern': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareBatchAccessPattern,
                    request_deserializer=superdl_dot_asyncgrpc_dot_protos_dot_cache__coordinator__pb2.BatchAccessPatternList.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CacheCoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CacheCoordinatorService(object):
    """
    Command to create stub files:
    python -m grpc_tools.protoc --proto_path=. ./superdl/asyncgrpc/protos/cache_coordinator.proto --python_out=. --grpc_python_out=.
    """

    @staticmethod
    def ShareBatchAccessPattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CacheCoordinatorService/ShareBatchAccessPattern',
            superdl_dot_asyncgrpc_dot_protos_dot_cache__coordinator__pb2.BatchAccessPatternList.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
