gprc_server_address: localhost:50051
task: train
num_workers: 0
lr: 1e-4
arch: resnet18
weight_decay: 1e-4
momentum: 0.9
batch_size: 128
max_epochs: 2
dataset_name: cifar10
save_dir: mlworkloads/vision/out/cifar10
data_dir: mlworkloads/vision/data/cifar-10
log_dir: mlworkloads/vision/logs
log_interval: 1
always_save_checkpoint: False
source_system: "local"
#cache_host: "10.0.1.197"
cache_host: "localhost"
dry_run: False
data_profile: False
max_minibatches_per_epoch: 8
#full_epoch: False
no_eval: True
use_super: False
#gpus: 0
#deterministic: True